### ISSUE TITLE
I2C Status Register 2 Flag Definitions Unclear

### ISSUE THREAD

**Issue by JeroenAdO** [openwch/ch32v20x#13]
I'm having trouble understanding the definitions of the I2C status register 2 flags in the current code (ch32v20x_i2c.h). The definitions seem to be using a format like:

#define I2C_FLAG_TRA ((uint32_t)0x00040000)

This suggests that the I2C_FLAG_TRA flag checks for bit 18 in the register SR2, but the datasheet indicates that the TRA flag resides on bit 2.

Could someone clarify the following:

Is the current approach for defining flags the intended way?
If so, how does the defined value (e.g., 0x00040000) relate to checking a specific bit (bit 2) in the register?

Any explanation or guidance on this matter would be greatly appreciated, thanks.

**Comment by qiyongshuang** [comment]
I2C_FLAG_TRA ((uint32_t)0x00040000) will move right 16bit in I2C_GetFlagStatus() function.
![image](https://github.com/openwch/ch32v20x/assets/110513727/f02c742d-a53c-4981-8696-211203c2d08b)

**Comment by JeroenAdO** [comment]
Ok, thanks for your clarification. This answered my question.
