### ISSUE TITLE
Doubts about I2C_7bit_Interrupt_Mode examples

### ISSUE THREAD

**Issue by Lovmong** [openwch/ch32v20x#6]
There is no interrupt service function in the code of I2C_7bit_Interrupt_Mode. https://github.com/openwch/ch32v20x/blob/main/EVT/EXAM/I2C/I2C_7bit_Interrupt_Mode/User/main.c

**Comment by payday1991** [comment]
Check here:
https://github.com/openwch/ch32v20x/blob/main/EVT/EXAM/I2C/I2C_7bit_Interrupt_Mode/User/ch32v20x_it.c
